# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/radio/message/HdRadioStationInfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/radio/message/HdRadioStationInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.radio.message import HdRadioSisData_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioSisData__pb2
from aap_protobuf.service.radio.message import HdRadioPsdData_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioPsdData__pb2
from aap_protobuf.service.radio.message import HdAcquisionState_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdAcquisionState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/service/radio/message/HdRadioStationInfo.proto\x12\"aap_protobuf.service.radio.message\x1a\x37\x61\x61p_protobuf/service/radio/message/HdRadioSisData.proto\x1a\x37\x61\x61p_protobuf/service/radio/message/HdRadioPsdData.proto\x1a\x39\x61\x61p_protobuf/service/radio/message/HdAcquisionState.proto\"\x88\x02\n\x12HdRadioStationInfo\x12O\n\x11\x61\x63quisition_state\x18\x01 \x01(\x0e\x32\x34.aap_protobuf.service.radio.message.HdAcquisionState\x12\x1f\n\x17\x64igital_signal_strength\x18\x02 \x01(\x05\x12?\n\x03psd\x18\x03 \x01(\x0b\x32\x32.aap_protobuf.service.radio.message.HdRadioPsdData\x12?\n\x03sis\x18\x04 \x01(\x0b\x32\x32.aap_protobuf.service.radio.message.HdRadioSisDataB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.HdRadioStationInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_HDRADIOSTATIONINFO']._serialized_start=273
  _globals['_HDRADIOSTATIONINFO']._serialized_end=537
# @@protoc_insertion_point(module_scope)
