# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/radio/message/RadioStationMetaData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/radio/message/RadioStationMetaData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.radio.message import RdsData_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RdsData__pb2
from aap_protobuf.service.radio.message import HdRadioStationInfo_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioStationInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/radio/message/RadioStationMetaData.proto\x12\"aap_protobuf.service.radio.message\x1a\x30\x61\x61p_protobuf/service/radio/message/RdsData.proto\x1a;aap_protobuf/service/radio/message/HdRadioStationInfo.proto\"\xd1\x01\n\x14RadioStationMetaData\x12\x16\n\x0e\x61udio_channels\x18\x01 \x01(\x05\x12\x16\n\x0esignal_quality\x18\x02 \x01(\x05\x12\x38\n\x03rds\x18\x03 \x01(\x0b\x32+.aap_protobuf.service.radio.message.RdsData\x12O\n\x0fhd_station_info\x18\x04 \x01(\x0b\x32\x36.aap_protobuf.service.radio.message.HdRadioStationInfoB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RadioStationMetaData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_RADIOSTATIONMETADATA']._serialized_start=213
  _globals['_RADIOSTATIONMETADATA']._serialized_end=422
# @@protoc_insertion_point(module_scope)
