# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/radio/message/StationPresetsNotification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/radio/message/StationPresetsNotification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.radio.message import StationPresetList_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_StationPresetList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/radio/message/StationPresetsNotification.proto\x12\"aap_protobuf.service.radio.message\x1a:aap_protobuf/service/radio/message/StationPresetList.proto\"i\n\x1aStationPresetsNotification\x12K\n\x0cpreset_lists\x18\x02 \x03(\x0b\x32\x35.aap_protobuf.service.radio.message.StationPresetListB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.StationPresetsNotification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_STATIONPRESETSNOTIFICATION']._serialized_start=167
  _globals['_STATIONPRESETSNOTIFICATION']._serialized_end=272
# @@protoc_insertion_point(module_scope)
