# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/sensorsource/SensorSourceService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/sensorsource/SensorSourceService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.sensorsource.message import Sensor_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_Sensor__pb2
from aap_protobuf.service.sensorsource.message import FuelType_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_FuelType__pb2
from aap_protobuf.service.sensorsource.message import EvConnectorType_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_EvConnectorType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/service/sensorsource/SensorSourceService.proto\x12!aap_protobuf.service.sensorsource\x1a\x36\x61\x61p_protobuf/service/sensorsource/message/Sensor.proto\x1a\x38\x61\x61p_protobuf/service/sensorsource/message/FuelType.proto\x1a?aap_protobuf/service/sensorsource/message/EvConnectorType.proto\"\xb1\x02\n\x13SensorSourceService\x12\x42\n\x07sensors\x18\x01 \x03(\x0b\x32\x31.aap_protobuf.service.sensorsource.message.Sensor\x12!\n\x19location_characterization\x18\x02 \x01(\r\x12Q\n\x14supported_fuel_types\x18\x03 \x03(\x0e\x32\x33.aap_protobuf.service.sensorsource.message.FuelType\x12`\n\x1csupported_ev_connector_types\x18\x04 \x03(\x0e\x32:.aap_protobuf.service.sensorsource.message.EvConnectorType')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.SensorSourceService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORSOURCESERVICE']._serialized_start=278
  _globals['_SENSORSOURCESERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
