# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/inputsource/message/InputFeedback.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/inputsource/message/InputFeedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.inputsource.message import FeedbackEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_FeedbackEvent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/inputsource/message/InputFeedback.proto\x12(aap_protobuf.service.inputsource.message\x1a<aap_protobuf/service/inputsource/message/FeedbackEvent.proto\"W\n\rInputFeedback\x12\x46\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x37.aap_protobuf.service.inputsource.message.FeedbackEvent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.InputFeedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTFEEDBACK']._serialized_start=168
  _globals['_INPUTFEEDBACK']._serialized_end=255
# @@protoc_insertion_point(module_scope)
