# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/inputsource/message/KeyEvent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/inputsource/message/KeyEvent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/inputsource/message/KeyEvent.proto\x12(aap_protobuf.service.inputsource.message\"\x9c\x01\n\x08KeyEvent\x12\x44\n\x04keys\x18\x01 \x03(\x0b\x32\x36.aap_protobuf.service.inputsource.message.KeyEvent.Key\x1aJ\n\x03Key\x12\x0f\n\x07keycode\x18\x01 \x02(\r\x12\x0c\n\x04\x64own\x18\x02 \x02(\x08\x12\x11\n\tmetastate\x18\x03 \x02(\r\x12\x11\n\tlongpress\x18\x04 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.KeyEvent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYEVENT']._serialized_start=102
  _globals['_KEYEVENT']._serialized_end=258
  _globals['_KEYEVENT_KEY']._serialized_start=184
  _globals['_KEYEVENT_KEY']._serialized_end=258
# @@protoc_insertion_point(module_scope)
