# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/inputsource/message/TouchEvent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/inputsource/message/TouchEvent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.inputsource.message import PointerAction_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_PointerAction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/inputsource/message/TouchEvent.proto\x12(aap_protobuf.service.inputsource.message\x1a<aap_protobuf/service/inputsource/message/PointerAction.proto\"\xf4\x01\n\nTouchEvent\x12R\n\x0cpointer_data\x18\x01 \x03(\x0b\x32<.aap_protobuf.service.inputsource.message.TouchEvent.Pointer\x12\x14\n\x0c\x61\x63tion_index\x18\x02 \x01(\r\x12G\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x37.aap_protobuf.service.inputsource.message.PointerAction\x1a\x33\n\x07Pointer\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12\x12\n\npointer_id\x18\x03 \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.TouchEvent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOUCHEVENT']._serialized_start=166
  _globals['_TOUCHEVENT']._serialized_end=410
  _globals['_TOUCHEVENT_POINTER']._serialized_start=359
  _globals['_TOUCHEVENT_POINTER']._serialized_end=410
# @@protoc_insertion_point(module_scope)
