# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/bluetooth/message/BluetoothPairingResponse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/bluetooth/message/BluetoothPairingResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.shared import MessageStatus_pb2 as aap__protobuf_dot_shared_dot_MessageStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEaap_protobuf/service/bluetooth/message/BluetoothPairingResponse.proto\x12&aap_protobuf.service.bluetooth.message\x1a\'aap_protobuf/shared/MessageStatus.proto\"f\n\x18\x42luetoothPairingResponse\x12\x32\n\x06status\x18\x01 \x02(\x0e\x32\".aap_protobuf.shared.MessageStatus\x12\x16\n\x0e\x61lready_paired\x18\x02 \x02(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.message.BluetoothPairingResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHPAIRINGRESPONSE']._serialized_start=154
  _globals['_BLUETOOTHPAIRINGRESPONSE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
