# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/bluetooth/message/BluetoothPairingRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/bluetooth/message/BluetoothPairingRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.bluetooth.message import BluetoothPairingMethod_pb2 as aap__protobuf_dot_service_dot_bluetooth_dot_message_dot_BluetoothPairingMethod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDaap_protobuf/service/bluetooth/message/BluetoothPairingRequest.proto\x12&aap_protobuf.service.bluetooth.message\x1a\x43\x61\x61p_protobuf/service/bluetooth/message/BluetoothPairingMethod.proto\"\x88\x01\n\x17\x42luetoothPairingRequest\x12\x15\n\rphone_address\x18\x01 \x02(\t\x12V\n\x0epairing_method\x18\x02 \x02(\x0e\x32>.aap_protobuf.service.bluetooth.message.BluetoothPairingMethod')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.message.BluetoothPairingRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHPAIRINGREQUEST']._serialized_start=182
  _globals['_BLUETOOTHPAIRINGREQUEST']._serialized_end=318
# @@protoc_insertion_point(module_scope)
