# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/bluetooth/message/BluetoothPairingMethod.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/bluetooth/message/BluetoothPairingMethod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/bluetooth/message/BluetoothPairingMethod.proto\x12&aap_protobuf.service.bluetooth.message*\xc9\x01\n\x16\x42luetoothPairingMethod\x12*\n\x1d\x42LUETOOTH_PAIRING_UNAVAILABLE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n\x15\x42LUETOOTH_PAIRING_OOB\x10\x01\x12(\n$BLUETOOTH_PAIRING_NUMERIC_COMPARISON\x10\x02\x12#\n\x1f\x42LUETOOTH_PAIRING_PASSKEY_ENTRY\x10\x03\x12\x19\n\x15\x42LUETOOTH_PAIRING_PIN\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.message.BluetoothPairingMethod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHPAIRINGMETHOD']._serialized_start=112
  _globals['_BLUETOOTHPAIRINGMETHOD']._serialized_end=313
# @@protoc_insertion_point(module_scope)
