# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/mediabrowser/message/MediaList.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/mediabrowser/message/MediaList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/mediabrowser/message/MediaList.proto\x12)aap_protobuf.service.mediabrowser.message\"\xd5\x01\n\tMediaList\x12\x0c\n\x04path\x18\x01 \x02(\t\x12G\n\x04type\x18\x02 \x02(\x0e\x32\x39.aap_protobuf.service.mediabrowser.message.MediaList.Type\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\talbum_art\x18\x04 \x01(\x0c\"P\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08PLAYLIST\x10\x01\x12\t\n\x05\x41LBUM\x10\x02\x12\n\n\x06\x41RTIST\x10\x03\x12\x0b\n\x07STATION\x10\x04\x12\t\n\x05GENRE\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.message.MediaList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIALIST']._serialized_start=105
  _globals['_MEDIALIST']._serialized_end=318
  _globals['_MEDIALIST_TYPE']._serialized_start=238
  _globals['_MEDIALIST_TYPE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
