# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/aaw/WifiStartResponse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/aaw/WifiStartResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.aaw import Status_pb2 as aap__protobuf_dot_aaw_dot_Status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(aap_protobuf/aaw/WifiStartResponse.proto\x12\x10\x61\x61p_protobuf.aaw\x1a\x1d\x61\x61p_protobuf/aaw/Status.proto\"_\n\x11WifiStartResponse\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12(\n\x06status\x18\x03 \x02(\x0e\x32\x18.aap_protobuf.aaw.Status')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.WifiStartResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFISTARTRESPONSE']._serialized_start=93
  _globals['_WIFISTARTRESPONSE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
