# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/media/source/MediaSourceService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/media/source/MediaSourceService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.media.shared.message import MediaCodecType_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_MediaCodecType__pb2
from aap_protobuf.service.media.shared.message import AudioConfiguration_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_AudioConfiguration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/media/source/MediaSourceService.proto\x12!aap_protobuf.service.media.source\x1a>aap_protobuf/service/media/shared/message/MediaCodecType.proto\x1a\x42\x61\x61p_protobuf/service/media/shared/message/AudioConfiguration.proto\"\xf4\x01\n\x12MediaSourceService\x12h\n\x0e\x61vailable_type\x18\x01 \x01(\x0e\x32\x39.aap_protobuf.service.media.shared.message.MediaCodecType:\x15MEDIA_CODEC_AUDIO_PCM\x12S\n\x0c\x61udio_config\x18\x02 \x01(\x0b\x32=.aap_protobuf.service.media.shared.message.AudioConfiguration\x12\x1f\n\x17\x61vailable_while_in_call\x18\x03 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.source.MediaSourceService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIASOURCESERVICE']._serialized_start=230
  _globals['_MEDIASOURCESERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
