# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/AudioFocusStateType.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/AudioFocusStateType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>aap_protobuf/service/control/message/AudioFocusStateType.proto\x12$aap_protobuf.service.control.message*\xc2\x02\n\x13\x41udioFocusStateType\x12\x1d\n\x19\x41UDIO_FOCUS_STATE_INVALID\x10\x00\x12\x1a\n\x16\x41UDIO_FOCUS_STATE_GAIN\x10\x01\x12$\n AUDIO_FOCUS_STATE_GAIN_TRANSIENT\x10\x02\x12\x1a\n\x16\x41UDIO_FOCUS_STATE_LOSS\x10\x03\x12-\n)AUDIO_FOCUS_STATE_LOSS_TRANSIENT_CAN_DUCK\x10\x04\x12$\n AUDIO_FOCUS_STATE_LOSS_TRANSIENT\x10\x05\x12%\n!AUDIO_FOCUS_STATE_GAIN_MEDIA_ONLY\x10\x06\x12\x32\n.AUDIO_FOCUS_STATE_GAIN_TRANSIENT_GUIDANCE_ONLY\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.AudioFocusStateType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFOCUSSTATETYPE']._serialized_start=105
  _globals['_AUDIOFOCUSSTATETYPE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
