# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/AudioFocusRequestNotification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/AudioFocusRequestNotification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.control.message import AudioFocusRequestType_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_AudioFocusRequestType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHaap_protobuf/service/control/message/AudioFocusRequestNotification.proto\x12$aap_protobuf.service.control.message\x1a@aap_protobuf/service/control/message/AudioFocusRequestType.proto\"m\n\x1d\x41udioFocusRequestNotification\x12L\n\x07request\x18\x01 \x02(\x0e\x32;.aap_protobuf.service.control.message.AudioFocusRequestType')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.AudioFocusRequestNotification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFOCUSREQUESTNOTIFICATION']._serialized_start=180
  _globals['_AUDIOFOCUSREQUESTNOTIFICATION']._serialized_end=289
# @@protoc_insertion_point(module_scope)
