# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/CallAvailabilityStatus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/CallAvailabilityStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/control/message/CallAvailabilityStatus.proto\x12$aap_protobuf.service.control.message\"0\n\x16\x43\x61llAvailabilityStatus\x12\x16\n\x0e\x63\x61ll_available\x18\x01 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.CallAvailabilityStatus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLAVAILABILITYSTATUS']._serialized_start=107
  _globals['_CALLAVAILABILITYSTATUS']._serialized_end=155
# @@protoc_insertion_point(module_scope)
