# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/CarConnectedDevices.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/CarConnectedDevices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.control.message import ConnectedDevice_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ConnectedDevice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>aap_protobuf/service/control/message/CarConnectedDevices.proto\x12$aap_protobuf.service.control.message\x1a:aap_protobuf/service/control/message/ConnectedDevice.proto\"\x96\x01\n\x13\x43\x61rConnectedDevices\x12P\n\x11\x63onnected_devices\x18\x01 \x03(\x0b\x32\x35.aap_protobuf.service.control.message.ConnectedDevice\x12\x13\n\x0bunsolicited\x18\x02 \x01(\x08\x12\x18\n\nfinal_list\x18\x03 \x01(\x08:\x04true')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.CarConnectedDevices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARCONNECTEDDEVICES']._serialized_start=165
  _globals['_CARCONNECTEDDEVICES']._serialized_end=315
# @@protoc_insertion_point(module_scope)
