# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/DriverPosition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/DriverPosition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/control/message/DriverPosition.proto\x12$aap_protobuf.service.control.message*~\n\x0e\x44riverPosition\x12\x18\n\x14\x44RIVER_POSITION_LEFT\x10\x00\x12\x19\n\x15\x44RIVER_POSITION_RIGHT\x10\x01\x12\x1a\n\x16\x44RIVER_POSITION_CENTER\x10\x02\x12\x1b\n\x17\x44RIVER_POSITION_UNKNOWN\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.DriverPosition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVERPOSITION']._serialized_start=99
  _globals['_DRIVERPOSITION']._serialized_end=225
# @@protoc_insertion_point(module_scope)
