# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/NavFocusRequestNotification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/NavFocusRequestNotification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.control.message import NavFocusType_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_NavFocusType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFaap_protobuf/service/control/message/NavFocusRequestNotification.proto\x12$aap_protobuf.service.control.message\x1a\x37\x61\x61p_protobuf/service/control/message/NavFocusType.proto\"e\n\x1bNavFocusRequestNotification\x12\x46\n\nfocus_type\x18\x01 \x01(\x0e\x32\x32.aap_protobuf.service.control.message.NavFocusType')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.NavFocusRequestNotification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVFOCUSREQUESTNOTIFICATION']._serialized_start=169
  _globals['_NAVFOCUSREQUESTNOTIFICATION']._serialized_end=270
# @@protoc_insertion_point(module_scope)
