# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/PingConfiguration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/PingConfiguration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/control/message/PingConfiguration.proto\x12$aap_protobuf.service.control.message\"{\n\x11PingConfiguration\x12\x12\n\ntimeout_ms\x18\x01 \x01(\r\x12\x13\n\x0binterval_ms\x18\x02 \x01(\r\x12!\n\x19high_latency_threshold_ms\x18\x03 \x01(\r\x12\x1a\n\x12tracked_ping_count\x18\x04 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.PingConfiguration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGCONFIGURATION']._serialized_start=102
  _globals['_PINGCONFIGURATION']._serialized_end=225
# @@protoc_insertion_point(module_scope)
