# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/VersionResponseOptions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/VersionResponseOptions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.control.message import ConnectionConfiguration_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ConnectionConfiguration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/control/message/VersionResponseOptions.proto\x12$aap_protobuf.service.control.message\x1a\x42\x61\x61p_protobuf/service/control/message/ConnectionConfiguration.proto\"y\n\x16VersionResponseOptions\x12_\n\x18\x63onnection_configuration\x18\x01 \x01(\x0b\x32=.aap_protobuf.service.control.message.ConnectionConfiguration')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.VersionResponseOptions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONRESPONSEOPTIONS']._serialized_start=175
  _globals['_VERSIONRESPONSEOPTIONS']._serialized_end=296
# @@protoc_insertion_point(module_scope)
