# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/control/message/VoiceSessionNotification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/control/message/VoiceSessionNotification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.control.message import VoiceSessionStatus_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_VoiceSessionStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/control/message/VoiceSessionNotification.proto\x12$aap_protobuf.service.control.message\x1a=aap_protobuf/service/control/message/VoiceSessionStatus.proto\"d\n\x18VoiceSessionNotification\x12H\n\x06status\x18\x01 \x01(\x0e\x32\x38.aap_protobuf.service.control.message.VoiceSessionStatus')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.VoiceSessionNotification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICESESSIONNOTIFICATION']._serialized_start=172
  _globals['_VOICESESSIONNOTIFICATION']._serialized_end=272
# @@protoc_insertion_point(module_scope)
