# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/media/shared/message/Config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/media/shared/message/Config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6aap_protobuf/service/media/shared/message/Config.proto\x12)aap_protobuf.service.media.shared.message\"\xb3\x01\n\x06\x43onfig\x12H\n\x06status\x18\x01 \x02(\x0e\x32\x38.aap_protobuf.service.media.shared.message.Config.Status\x12\x13\n\x0bmax_unacked\x18\x02 \x01(\r\x12\x1d\n\x15\x63onfiguration_indices\x18\x03 \x03(\r\"+\n\x06Status\x12\x0f\n\x0bSTATUS_WAIT\x10\x01\x12\x10\n\x0cSTATUS_READY\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.Config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=102
  _globals['_CONFIG']._serialized_end=281
  _globals['_CONFIG_STATUS']._serialized_start=238
  _globals['_CONFIG_STATUS']._serialized_end=281
# @@protoc_insertion_point(module_scope)
