# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/media/shared/message/MediaCodecType.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/media/shared/message/MediaCodecType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>aap_protobuf/service/media/shared/message/MediaCodecType.proto\x12)aap_protobuf.service.media.shared.message*\xdd\x01\n\x0eMediaCodecType\x12\x19\n\x15MEDIA_CODEC_AUDIO_PCM\x10\x01\x12\x1c\n\x18MEDIA_CODEC_AUDIO_AAC_LC\x10\x02\x12\x1d\n\x19MEDIA_CODEC_VIDEO_H264_BP\x10\x03\x12!\n\x1dMEDIA_CODEC_AUDIO_AAC_LC_ADTS\x10\x04\x12\x19\n\x15MEDIA_CODEC_VIDEO_VP9\x10\x05\x12\x19\n\x15MEDIA_CODEC_VIDEO_AV1\x10\x06\x12\x1a\n\x16MEDIA_CODEC_VIDEO_H265\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.MediaCodecType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIACODECTYPE']._serialized_start=110
  _globals['_MEDIACODECTYPE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
