# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/media/video/message/VideoFocusRequestNotification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/media/video/message/VideoFocusRequestNotification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.media.video.message import VideoFocusMode_pb2 as aap__protobuf_dot_service_dot_media_dot_video_dot_message_dot_VideoFocusMode__pb2
from aap_protobuf.service.media.video.message import VideoFocusReason_pb2 as aap__protobuf_dot_service_dot_media_dot_video_dot_message_dot_VideoFocusReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLaap_protobuf/service/media/video/message/VideoFocusRequestNotification.proto\x12(aap_protobuf.service.media.video.message\x1a=aap_protobuf/service/media/video/message/VideoFocusMode.proto\x1a?aap_protobuf/service/media/video/message/VideoFocusReason.proto\"\xd0\x01\n\x1dVideoFocusRequestNotification\x12\x1b\n\x0f\x64isp_channel_id\x18\x01 \x01(\x05\x42\x02\x18\x01\x12\x46\n\x04mode\x18\x02 \x01(\x0e\x32\x38.aap_protobuf.service.media.video.message.VideoFocusMode\x12J\n\x06reason\x18\x03 \x01(\x0e\x32:.aap_protobuf.service.media.video.message.VideoFocusReason')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.video.message.VideoFocusRequestNotification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFOCUSREQUESTNOTIFICATION'].fields_by_name['disp_channel_id']._loaded_options = None
  _globals['_VIDEOFOCUSREQUESTNOTIFICATION'].fields_by_name['disp_channel_id']._serialized_options = b'\030\001'
  _globals['_VIDEOFOCUSREQUESTNOTIFICATION']._serialized_start=251
  _globals['_VIDEOFOCUSREQUESTNOTIFICATION']._serialized_end=459
# @@protoc_insertion_point(module_scope)
