# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/sensorsource/message/DrivingStatus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/sensorsource/message/DrivingStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/sensorsource/message/DrivingStatus.proto\x12)aap_protobuf.service.sensorsource.message*\xce\x01\n\rDrivingStatus\x12\x1d\n\x19\x44RIVE_STATUS_UNRESTRICTED\x10\x00\x12\x19\n\x15\x44RIVE_STATUS_NO_VIDEO\x10\x01\x12\"\n\x1e\x44RIVE_STATUS_NO_KEYBOARD_INPUT\x10\x02\x12\x1f\n\x1b\x44RIVE_STATUS_NO_VOICE_INPUT\x10\x04\x12\x1a\n\x16\x44RIVE_STATUS_NO_CONFIG\x10\x08\x12\"\n\x1e\x44RIVE_STATUS_LIMIT_MESSAGE_LEN\x10\x10')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.DrivingStatus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVINGSTATUS']._serialized_start=109
  _globals['_DRIVINGSTATUS']._serialized_end=315
# @@protoc_insertion_point(module_scope)
