# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/sensorsource/message/SensorErrorType.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/sensorsource/message/SensorErrorType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/sensorsource/message/SensorErrorType.proto\x12)aap_protobuf.service.sensorsource.message*X\n\x0fSensorErrorType\x12\r\n\tSENSOR_OK\x10\x01\x12\x1a\n\x16SENSOR_ERROR_TRANSIENT\x10\x02\x12\x1a\n\x16SENSOR_ERROR_PERMANENT\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.SensorErrorType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORERRORTYPE']._serialized_start=110
  _globals['_SENSORERRORTYPE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
