# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/sensorsource/message/SensorError.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/sensorsource/message/SensorError.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.sensorsource.message import SensorType_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_SensorType__pb2
from aap_protobuf.service.sensorsource.message import SensorErrorType_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_SensorErrorType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/service/sensorsource/message/SensorError.proto\x12)aap_protobuf.service.sensorsource.message\x1a:aap_protobuf/service/sensorsource/message/SensorType.proto\x1a?aap_protobuf/service/sensorsource/message/SensorErrorType.proto\"\xb0\x01\n\x0bSensorError\x12J\n\x0bsensor_type\x18\x01 \x02(\x0e\x32\x35.aap_protobuf.service.sensorsource.message.SensorType\x12U\n\x11sensor_error_type\x18\x02 \x02(\x0e\x32:.aap_protobuf.service.sensorsource.message.SensorErrorType')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.SensorError_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORERROR']._serialized_start=232
  _globals['_SENSORERROR']._serialized_end=408
# @@protoc_insertion_point(module_scope)
