# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/channel/control/GalVerificationVendorExtensionMessageId.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/channel/control/GalVerificationVendorExtensionMessageId.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJaap_protobuf/channel/control/GalVerificationVendorExtensionMessageId.proto\x12$aap_protobuf.service.control.message*\x82\x04\n\'GalVerificationVendorExtensionMessageId\x12!\n\x1bGAL_VERIFICATION_SET_SENSOR\x10\x81\x80\x02\x12(\n\"GAL_VERIFICATION_MEDIA_SINK_STATUS\x10\x82\x80\x02\x12\"\n\x1cGAL_VERIFICATION_VIDEO_FOCUS\x10\x83\x80\x02\x12\"\n\x1cGAL_VERIFICATION_AUDIO_FOCUS\x10\x84\x80\x02\x12#\n\x1dGAL_VERIFICATION_INJECT_INPUT\x10\x85\x80\x02\x12)\n#GAL_VERIFICATION_BUG_REPORT_REQUEST\x10\x86\x80\x02\x12*\n$GAL_VERIFICATION_BUG_REPORT_RESPONSE\x10\x87\x80\x02\x12-\n\'GAL_VERIFICATION_SCREEN_CAPTURE_REQUEST\x10\x88\x80\x02\x12.\n(GAL_VERIFICATION_SCREEN_CAPTURE_RESPONSE\x10\x89\x80\x02\x12\x32\n,GAL_VERIFICATION_DISPLAY_INFORMATION_REQUEST\x10\x8a\x80\x02\x12\x33\n-GAL_VERIFICATION_DISPLAY_INFORMATION_RESPONSE\x10\x8b\x80\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationVendorExtensionMessageId_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GALVERIFICATIONVENDOREXTENSIONMESSAGEID']._serialized_start=117
  _globals['_GALVERIFICATIONVENDOREXTENSIONMESSAGEID']._serialized_end=631
# @@protoc_insertion_point(module_scope)
