# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/channel/control/GalVerificationAudioFocus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/channel/control/GalVerificationAudioFocus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aap_protobuf.service.control.message import AudioFocusStateType_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_AudioFocusStateType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/channel/control/GalVerificationAudioFocus.proto\x12$aap_protobuf.service.control.message\x1a>aap_protobuf/service/control/message/AudioFocusStateType.proto\"\x97\x01\n\x19GalVerificationAudioFocus\x12T\n\x11\x61udio_focus_state\x18\x01 \x02(\x0e\x32\x39.aap_protobuf.service.control.message.AudioFocusStateType\x12\x0f\n\x07\x63hannel\x18\x02 \x02(\x05\x12\x13\n\x0bunsolicited\x18\x03 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationAudioFocus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GALVERIFICATIONAUDIOFOCUS']._serialized_start=167
  _globals['_GALVERIFICATIONAUDIOFOCUS']._serialized_end=318
# @@protoc_insertion_point(module_scope)
