# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/channel/control/LocationCharacterization.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/channel/control/LocationCharacterization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/channel/control/LocationCharacterization.proto\x12\x13\x61\x61p_protobuf.shared*\xe3\x01\n\x18LocationCharacterization\x12\x13\n\x0fPRIOR_LOCATIONS\x10\x01\x12\x14\n\x10GYROSCOPE_FUSION\x10\x02\x12\x18\n\x14\x41\x43\x43\x45LEROMETER_FUSION\x10\x04\x12\x12\n\x0e\x43OMPASS_FUSION\x10\x08\x12\x16\n\x12WHEEL_SPEED_FUSION\x10\x10\x12\x19\n\x15STEERING_ANGLE_FUSION\x10 \x12\x14\n\x10\x43\x41R_SPEED_FUSION\x10@\x12\x12\n\rDEAD_RECKONED\x10\x80\x01\x12\x11\n\x0cRAW_GPS_ONLY\x10\x80\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.LocationCharacterization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONCHARACTERIZATION']._serialized_start=85
  _globals['_LOCATIONCHARACTERIZATION']._serialized_end=312
# @@protoc_insertion_point(module_scope)
