# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/media/sink/message/AudioStreamType.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/media/sink/message/AudioStreamType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/media/sink/message/AudioStreamType.proto\x12\'aap_protobuf.service.media.sink.message*\x7f\n\x0f\x41udioStreamType\x12\x19\n\x15\x41UDIO_STREAM_GUIDANCE\x10\x01\x12\x1d\n\x19\x41UDIO_STREAM_SYSTEM_AUDIO\x10\x02\x12\x16\n\x12\x41UDIO_STREAM_MEDIA\x10\x03\x12\x1a\n\x16\x41UDIO_STREAM_TELEPHONY\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.AudioStreamType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOSTREAMTYPE']._serialized_start=106
  _globals['_AUDIOSTREAMTYPE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
