# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aap_protobuf/service/phonestatus/PhoneStatusMessageId.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aap_protobuf/service/phonestatus/PhoneStatusMessageId.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/service/phonestatus/PhoneStatusMessageId.proto\x12 aap_protobuf.service.phonestatus*D\n\x14PhoneStatusMessageId\x12\x12\n\x0cPHONE_STATUS\x10\x81\x80\x02\x12\x18\n\x12PHONE_STATUS_INPUT\x10\x82\x80\x02\x42\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.phonestatus.PhoneStatusMessageId_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_PHONESTATUSMESSAGEID']._serialized_start=97
  _globals['_PHONESTATUSMESSAGEID']._serialized_end=165
# @@protoc_insertion_point(module_scope)
